# Generated by Django 4.0.3 on 2022-06-21 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniquiz', '0002_alter_leaderboards_authorsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboards',
            name='authorsID',
            field=models.ForeignKey(default='bishal', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authorIdentity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='categoryIdentity',
            field=models.ForeignKey(default='Dummey', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_id', to='miniquiz.category'),
        ),
    ]
