# Generated by Django 4.0.3 on 2022-08-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniquiz', '0005_alter_answer_question_alter_category_categoryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboards',
            name='categoryIdentity',
            field=models.ForeignKey(default='4f0b25fa-b880-4cdb-8adb-1a8511147060', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_id', to='miniquiz.category'),
        ),
    ]
